version: 2
jobs:
  build:
    working_directory: ~/incident
    docker:
      - image: circleci/elixir:1.7.4
      - image: circleci/postgres:9.6.3
    environment:
      - MIX_ENV: "test"
    steps:
      - run:
          name: Elixir Version
          command: iex --version
          background: true
      - run:
          name: Erlang Version
          command: erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
          background: true
      - checkout
      - restore_cache:
          name: Restoring Mix Cache
          keys:
            - incident-v1-mix-cache-{{ checksum "mix.lock" }}-{{ .Branch }}
            - incident-v1-mix-cache-{{ checksum "mix.lock" }}
            - incident-v1-mix-cache
      - run:
          name: Install Hex
          command: mix local.hex --force
      - run:
          name: Install Rebar
          command: mix local.rebar
      - run:
          name: Install Dependencies
          command: mix deps.get
      - run:
          name: Compile Dependencies
          command: mix deps.compile
      - save_cache:
          name: Saving Mix Cache
          key: incident-v1-mix-cache-{{ checksum "mix.lock" }}-{{ .Branch }}
          paths:
            - ~/.mix
            - ~/.cache/rebar3/hex/default
            - _build
            - deps
      - save_cache:
          name: Saving Mix Cache
          key: incident-v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - ~/.mix
            - ~/.cache/rebar3/hex/default
            - _build
            - deps
      - save_cache:
          name: Saving Mix Cache
          key: incident-v1-mix-cache
          paths:
            - ~/.mix
            - ~/.cache/rebar3/hex/default
            - _build
            - deps
      - run:
          name: Compile
          command: mix compile --force
      - restore_cache:
          name: Restoring Dialyzer PLT Cache
          keys:
            - incident-v1-dialyzer-plt-cache-{{ checksum "mix.lock" }}-{{ .Branch }}
            - incident-v1-dialyzer-plt-cache-{{ checksum "mix.lock" }}
            - incident-v1-dialyzer-plt-cache
      - run:
          name: Build Dialyzer PLT
          command: mix dialyzer --plt
      - save_cache:
          name: Saving Dialyzer PLT Cache
          key: incident-v1-dialyzer-plt-cache-{{ checksum "mix.lock" }}-{{ .Branch }}
          paths:
            - ~/.mix
            - _build
      - save_cache:
          name: Saving Dialyzer PLT Cache
          key: incident-v1-dialyzer-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - ~/.mix
            - _build
      - save_cache:
          name: Saving Dialyzer PLT Cache
          key: incident-v1-dialyzer-plt-cache
          paths:
            - ~/.mix
            - _build
      - run:
          name: Create DB
          command: mix ecto.create
      - run:
          name: Migrate DB
          command: mix ecto.migrate
      - run:
          name: Format
          command:  mix format --check-formatted
      - run:
          name: Credo
          command: mix credo --strict
      - run:
          name: Coveralls
          command: mix coveralls
      - run:
          name: Test
          command: mix test
      - run:
          name: Dialyzer
          command: mix dialyzer --halt-exit-status
          no_output_timeout: 30m
